name: Build and Release

permissions:
  contents: write
  issues: write

on:
  push:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate-cddl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: proto

      - name: Install ZCBOR
        run:
          sudo apt update && sudo apt install python3-pip -y && pip3 install
          zcbor==0.7.0

      - name: Validate CDDL and convert JSON
        working-directory: proto/hello/firmware
        run: bash validate.sh

  main:
    runs-on: ubuntu-latest
    needs: [validate-cddl]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Check source code with eslint
        run: npx eslint ./

      - name: Check if source code is properly formatted
        run: npx prettier -c ./

      - name: Run tests
        run: npm test

      - name: Run example
        run: npx tsx example.ts

      - name: Semantic release
        run: npx semantic-release
