name: Build and Release

permissions:
  contents: write
  issues: write
  id-token: write

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: ">=24.19.0 <25"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM version specified in package.json
        uses: ./.github/actions/install-npm

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Check source code with eslint
        run: npx eslint ./

      - name: Check if source code is properly formatted
        run: npx prettier -c ./

      - name: Run tests
        run: npm test

      - name: Semantic release
        run: npx semantic-release
